version: '3.1'
services:
  database:
    container_name: api_database
    image: postgres
    restart: always
    networks:
      - db
    env_file:
      - .env
    environment:
      POSTGRES_USER : ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - "5432:5432"

  webadmin:
    image: adminer
    restart: on-failure
    ports:
      - "18080:8080"
    networks:
      - db


networks:
  db:
